name: test

on:
  pull_request:
    branches:
      - master
      - dev

    # Only run if src, pom or github actions files change
    # Other changes like docs / readme / license don't require tests to be re-run
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/**'

  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/**'

# Prevent multiple runs of the same workflow on the same branch at the same time
# e.g. if new commits pushed to a PR, will cancel any current runs before starting
# a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    # Cancel jobs after 30 minutes
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: maven

#      - name: Install blosc
#        run: sudo apt install libblosc-dev
      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Build with maven
#        env:
#          MAVEN_OPTS: "-Xmx2048m"
        run: xvfb-run --auto-servernum mvn -B package --file pom.xml
